sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-25.0.0

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew clean assembleDebug testDebug

